#!/bin/bash
rm -r ./dist
mkdir ./dist
tsc --target "ES6" --outFile ./dist/clinamen-bt.js ./src/interfaces.ts  ./src/util.ts ./src/node.ts ./src/composite.ts ./src/decorator.ts  ./src/action.ts ./src/agent.ts

#
